"""add video columns to image_prompts

Revision ID: 665a79b5a541
Revises: e3aead73a2b8
Create Date: 2026-09-22 19:39:05.891770

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '665a79b5a541'
down_revision: str | None = 'e3aead73a2b8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # server_default='' necessário aqui (e não só no ORM) porque projetos
    # anteriores à Fase 5 já têm linhas em `image_prompts` — sem um valor
    # padrão no schema, a migração falharia numa coluna NOT NULL contra um
    # banco com dados. (SQLite não suporta ALTER COLUMN fora de batch mode,
    # não configurado aqui — por isso o default fica no schema para sempre,
    # em vez de só de passagem.)
    op.add_column(
        'image_prompts', sa.Column('video_prompt_text', sa.Text(), nullable=False, server_default='')
    )
    op.add_column('image_prompts', sa.Column('video_path', sa.String(length=500), nullable=True))
    op.add_column('image_prompts', sa.Column('video_uploaded_at', sa.DateTime(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_prompts', 'video_uploaded_at')
    op.drop_column('image_prompts', 'video_path')
    op.drop_column('image_prompts', 'video_prompt_text')
    # ### end Alembic commands ###
