"""add image_prompts table

Revision ID: a8b81dec95bd
Revises: 912f8f12b117
Create Date: 2026-09-10 07:18:33.244793

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'a8b81dec95bd'
down_revision: str | None = '912f8f12b117'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_prompts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=80), nullable=False),
    sa.Column('scene_id', sa.String(length=40), nullable=False),
    sa.Column('global_order', sa.Integer(), nullable=False),
    sa.Column('order_in_scene', sa.Integer(), nullable=False),
    sa.Column('shot_type', sa.String(length=60), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('image_uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_prompts')
    # ### end Alembic commands ###
